export default {
	REGISTER_USER: 'REGISTER_USER',
	REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
	REGISTER_USER_REDIRECT: 'REGISTER_USER_REDIRECT',
	REGISTER_USER_MESSAGE: 'REGISTER_USER_MESSAGE',
	GET_FLIGHTS: 'GET_FLIGHTS',
	REGISTER_USER_DETAILS: 'REGISTER_USER_DETAILS',
	LOGIN_USER_DETAILS: 'LOGIN_USER_DETAILS',
	LOGIN_USER_ERROR: 'LOGIN_USER_ERROR'
};
